# Generated by Django 4.2.21 on 2025-06-17 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=200, null=True)),
                ('provider', models.TextField(blank=True, choices=[('NETH', 'NETH'), ('MOBPLUS', 'MOBPLUS'), ('GOOGLE', 'GOOGLE'), ('ANGELMEDIA', 'ANGELMEDIA'), ('CLICKBYTE', 'CLICKBYTE'), ('VISIONTREK', 'VISIONTREK')], null=True, verbose_name='provider')),
                ('occurence', models.IntegerField(default=1)),
                ('remarketed', models.BooleanField(default=False)),
                ('last_subscribtion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignNotificationBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=200, null=True)),
                ('partner', models.CharField(blank=True, max_length=200, null=True)),
                ('click_id', models.CharField(blank=True, max_length=200, null=True)),
                ('telco', models.CharField(blank=True, max_length=200, null=True)),
                ('req_body', models.TextField(blank=True, null=True)),
                ('provider', models.TextField(choices=[('NETH', 'NETH'), ('MOBPLUS', 'MOBPLUS'), ('GOOGLE', 'GOOGLE'), ('ANGELMEDIA', 'ANGELMEDIA'), ('CLICKBYTE', 'CLICKBYTE'), ('VISIONTREK', 'VISIONTREK')], default='NETH', verbose_name='provider')),
                ('pubid', models.CharField(blank=True, max_length=200, null=True)),
                ('amt', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('occurence', models.IntegerField(default=0)),
                ('converted', models.BooleanField(default=False)),
                ('is_convertable', models.BooleanField(default=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('test_phase', models.CharField(choices=[('live_prod', 'Live Prod'), ('phase_one', 'Phase One'), ('phase_two', 'Phase Two'), ('beta', 'Beta')], default='live_prod', max_length=200)),
                ('traffic_source', models.CharField(blank=True, choices=[('NETH', 'NETH'), ('MOBPLUS', 'MOBPLUS'), ('GOOGLE', 'GOOGLE'), ('ANGELMEDIA', 'ANGELMEDIA'), ('CLICKBYTE', 'CLICKBYTE'), ('VISIONTREK', 'VISIONTREK')], max_length=100, null=True, verbose_name='traffic_source')),
                ('sub_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('no_sub', 'No Subscribtion')], default='no_sub', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_alias', models.CharField(blank=True, max_length=250, null=True)),
                ('company_banner', models.ImageField(blank=True, null=True, upload_to='vendor/banner/')),
                ('company_thumbnail', models.ImageField(blank=True, null=True, upload_to='vendor/thumbnail/')),
                ('onboarded', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_body', models.TextField(blank=True, null=True)),
                ('telco', models.CharField(blank=True, max_length=20, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_active', models.BooleanField(default=False)),
                ('starts_date', models.DateTimeField(blank=True, null=True)),
                ('ends_date', models.DateTimeField(blank=True, null=True)),
                ('first_sub', models.BooleanField(default=False)),
                ('renewal_sub', models.BooleanField(default=False)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('traffic_source', models.CharField(blank=True, choices=[('NETH', 'NETH'), ('MOBPLUS', 'MOBPLUS'), ('GOOGLE', 'GOOGLE'), ('ANGELMEDIA', 'ANGELMEDIA'), ('CLICKBYTE', 'CLICKBYTE'), ('VISIONTREK', 'VISIONTREK')], max_length=100, null=True, verbose_name='traffic_source')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ums.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DataSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('telco', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_not_type', models.CharField(blank=True, max_length=100, null=True)),
                ('product_sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('sub_date', models.DateTimeField(blank=True, null=True)),
                ('sub_expiry', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('telco_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('bearer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign_tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ums.campaigntracker')),
                ('webhook_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ums.webhookbackup')),
            ],
        ),
    ]
