# Generated by Django 4.2.21 on 2026-02-11 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=200, null=True)),
                ('activation', models.IntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('trx_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence_no', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Raw callback payload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Callback notification',
                'verbose_name_plural': 'Callback notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
