# Generated by Django 4.2.21 on 2025-06-17 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='Lorem Ipsum')),
                ('img_banner', models.ImageField(blank=True, upload_to='ballershub-podcast/content_images/banner/')),
                ('img_poster', models.ImageField(blank=True, upload_to='ballershub-podcast/content_images/poster/')),
                ('img_detail_poster', models.ImageField(blank=True, upload_to='ballershub-podcast/content_images/poster/')),
                ('img_detail_banner', models.ImageField(blank=True, upload_to='ballershub-podcast/content_images/banner/')),
                ('img_trailer', models.ImageField(blank=True, upload_to='ballershub-podcast/content_images/trailer/')),
                ('img_thumbnail', models.ImageField(blank=True, upload_to='ballershub-podcast/content_images/thumbnai/')),
                ('trailer_mp4', models.FileField(blank=True, upload_to='ballershub-podcast/content_file/trailer/mp4/')),
                ('file_mp4', models.FileField(blank=True, upload_to='ballershub-podcast/content_file/mp4/')),
                ('upload_date', models.DateField(blank=True)),
                ('timedelta', models.DurationField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('watch_times', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contentcategory')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contentgenre')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='WatchedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_content', to='content.episode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_content', to='ums.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='channel/banner')),
                ('banner_slit_1', models.ImageField(blank=True, null=True, upload_to='channel/banner')),
                ('banner_slit_2', models.ImageField(blank=True, null=True, upload_to='channel/banner')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='channel/thumbnail')),
                ('total_views', models.IntegerField(default=0)),
                ('admin_favorite', models.BooleanField(default=False)),
                ('default_channel', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='show_episodes', to='content.show'),
        ),
    ]
